---
hostname: HQ-ASW7

users:
  - username: admin
    privilege_level: 15
    password: TestPassword123!

vlans:
  - id: 70
    description: IT
  - id: 110
    description: Management-Plane
  - id: 1001
    description: native-vlan

interfaces:
  - name: Ethernet0/0
    description: Management
    mode: access
    access_vlan: 110

  - name: Ethernet0/1
    description: Link HQ-DSW5
    channel_group:
      id: 1
      mode: active

  - name: Ethernet0/2
    description: Link HQ-DSW5
    channel_group:
      id: 1
      mode: active

  - name: Ethernet0/3
    description: Link HQ-DSW6
    channel_group:
      id: 2
      mode: active

  - name: Ethernet1/0
    description: Link HQ-DSW6
    channel_group:
      id: 2
      mode: active

  - name: Ethernet1/1
    description: PC1
    mode: access
    access_vlan: 70
    portfast: true
    bpduguard: true

  - name: Ethernet1/2
    description: PC2
    mode: access
    access_vlan: 70
    portfast: true
    bpduguard: true

  - name: port-channel1
    description: LACP HQ-DSW5
    mode: trunk
    allowed_vlans: 70
    native_vlan: 1001

  - name: port-channel2
    description: LACP HQ-DSW6
    mode: trunk
    allowed_vlans: 70
    native_vlan: 1001

  - name: vlan110
    description: management-interface
    ip_address: 192.168.110.19
    mask: 255.255.255.0
    shutdown: false
