all:
  vars:
    ansible_user: admin
    ansible_password: TestPassword123!
    ansible_port: 22
    ansible_connection: network_cli
    ansible_network_os: cisco.ios.ios
  children:
    routers:
      hosts:
        Core-Router:
          ansible_host: 192.168.110.1
        HQ-Edge-Router:
          ansible_host: 192.168.110.2
        HQ-Router1:
          ansible_host: 192.168.110.3
        HQ-Router2:
          ansible_host: 192.168.110.4

    switches:
      hosts:
        HQ-CSW1:
          ansible_host: 192.168.110.5
        HQ-CSW2:
          ansible_host: 192.168.110.6
        HQ-DSW1:
          ansible_host: 192.168.110.7
        HQ-DSW2:
          ansible_host: 192.168.110.8
        HQ-DSW3:
          ansible_host: 192.168.110.9
        HQ-DSW4:
          ansible_host: 192.168.110.10
        HQ-DSW5:
          ansible_host: 192.168.110.11
        HQ-DSW6:
          ansible_host: 192.168.110.12
        HQ-ASW1:
          ansible_host: 192.168.110.13
        HQ-ASW2:
          ansible_host: 192.168.110.14
        HQ-ASW3:
          ansible_host: 192.168.110.15
        HQ-ASW4:
          ansible_host: 192.168.110.16
        HQ-ASW5:
          ansible_host: 192.168.110.17
        HQ-ASW6:
          ansible_host: 192.168.110.18
        HQ-ASW7:
          ansible_host: 192.168.110.19
        HQ-ASW8:
          ansible_host: 192.168.110.20
        HQ-ASW9:
          ansible_host: 192.168.110.21
