hostname: HQ-Edge-Router

interfaces:
  - name: Ethernet 0/3
    description: To Core-Router
    ip: 10.0.0.2
    mask: 255.255.255.252

  - name: Loopback0
    description: Router-ID
    ip: 2.2.2.2
    mask: 255.255.255.255
