---
- name: Configure Routers
  hosts: routers
  gather_facts: false

  roles:
    - base_config
    - switching

- name: Configure switches
  hosts: switches
  gather_facts: false

  roles:
    - base_config
    - switching
