- name: Generate switch configs
  hosts: routers
  gather_facts: false

  tasks:
    - name: Create local directory
      run_once: true
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ playbook_dir }}/generated_configs"
        state: directory
        mode: 0755

    - name: Generate configuration file
      delegate_to: localhost
      template:
        src: "templates/{{ config_template }}"
        dest: "{{ playbook_dir }}/generated_configs/{{ inventory_hostname }}.ios"
