---
- name: Pre-Flight Reachability Validation
  hosts: HQ-ASW1:HQ-ASW2:HQ-DSW1:HQ-DSW2:HQ-CSW1
  gather_facts: false
  connection: local

  tasks:
    - name: Ping management IP address
      ansible.builtin.command: "ping -c 3 {{ ansible_host }}"
      register: ping_result
      ignore_errors: true

    - name: Create local directory
      run_once: true
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{ playbook_dir }}/connection_status"
        state: directory
        mode: 0755

    - name: Save status for the python orchestrator
      ansible.builtin.copy:
        content: "{{ 'ONLINE' if ping_result.rc == 0 else 'OFFLINE' }}"
        dest: "{{ playbook_dir }}/connection_status/status_{{ inventory_hostname }}.txt"
